spring:
  datasource:
    url: jdbc:h2:mem:auth_test_db;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    discovery:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false


security:
  jwt:
    issuer: "http://localhost:8081"
    key-id: "auth-service-key-1"
    private-key: "classpath:keys/private.pem"
    public-key: "classpath:keys/public.pem"